sonar.projectKey=robert-tessnow-ramirez-sonar_vibe-terminal
sonar.organization=robert-tessnow-ramirez-sonar
sonar.scanner.sonarcloudUrl=https://sc-staging.io
sonar.scanner.apiBaseUrl=https://api.sc-staging.io


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=vibe-terminal
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
